# This is a basic workflow to help you get started with Actions

name: MLOps Automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]   

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'Set up python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: "install requirements"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: "Azure login"  
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: 'Run data prep script'
        working-directory: steps
        run: |
          python 01_DataPreparing.py
          
      - name: 'Run Training script'
        working-directory: steps
        run: |
          python 02_Training.py
          
      - name: 'Register model'
        working-directory: steps
        run: |
          python 03_RegisterModel.py
          
      - name: 'Deploy model'
        working-directory: steps
        run: |
          python 04_DeployModel.py
      
      - name: "Save config data"
        uses: actions/upload-artifact@v2.2.3
        with:
          name: config-data
          path: steps/root/config_states
          retention-days: 10
